### ISSUE TITLE
Additional info: Element 'Tp' is not valid for content model: '(Tp,Ref)

### ISSUE THREAD

**Issue by trco** [boris-savic/python_sepa#2]
Hey,

I'm getting this error when trying to perform transaction using XML constructed with your code:

Error parsing XML document (line=86, column=26)! Exception type: 'SAXParseException' Additional info: Element 'Tp' is not valid for content model: '(Tp,Ref).

Here is how I'm adding a transaction:
```
sepa_transfer.add_transaction(
    creditor=creditor,
    amount=Amount(Decimal(shop.total)),
    purpose='Invoice Payment',
    eref='SI992017-15',
    ext_purpose='OTHR',
    cref='SI0020170504058'
)
```

And here is Tp, Ref part of XML:
```
<CdtrRefInf>
    <Ref>SI992017-15</Ref>
    <Tp>
        <CdOrPrtry>
            <Cd>SCOR</Cd>
        </CdOrPrtry>
    </Tp>
</CdtrRefInf>
```

I have a working XML example, which has Tr and Ref elements in opposite order. Tp first and Ref second. I believe that the order matters. Any comments highly appreciated.

**Comment by boris-savic** [comment]
Hi, sorry for late response. I hope that you have solved the issue by now. 

With the information you've provided my guess would be that your bank uses different format? Perhaps you can try to manually change the order and check if that changes it. My guess is that SI99 does not accept 2017-15 part, perhaps you should try with SI002017-15 ?

**Comment by trco** [comment]
Boris, thank you for your response. I solved the issue by setting use_structured=False when calling sepa_transfer.add_transaction(). This omits Tr and Ref elements and the transaction is successful in my case. However I have another issue and I will open the new one for it.

**Comment by BenjoNX** [comment]
Hello, we have created software that generates your sepa xml file for transfers and direct debits in just one click, with a simple copy/paste into a google sheet: [sepaxml.com](http://sepaxml.com/) for €12/month
