### ISSUE TITLE
Random Ctry and AdrLine order prevents transaction

### ISSUE THREAD

**Issue by trco** [boris-savic/python_sepa#3]
Hey,

I have a problem with random order of Ctry and AdrLine elements inside of PstlAdr element. Sometimes the order is correct, while sometimes Ctry is between both AdrLines, which of course prevents successful transactions.

I have tried by setting address['_sorting'] = ['Ctry', 'AdrLine'] in def construct_address_data() function of your plugin, but I believe that there is still chance that two AdrLines would be in different order than required. I believe that construct_address_data() should be defined in such way that adress_line_1 would always be before address_line_2 when PstlAdr element is constructed.

Do you have any suggestions on how to tackle the problem without rewriting this part of your plugin?

**Comment by boris-savic** [comment]
I believe this is an issue with Python version you're running. Personally I haven't had this issue, You could submit a pull-request if you've managed to fix the library to provide the correct ordering or you could process the output XML in your code to assure the order is correct before exporting XML file. 

PS: Terribly sorry for such late responses. I seem to be having issues receiving Github emails :/
